version: "3.1"

services:
  reaper:
    build: reaper/
    ports:
      - 8000:8000
    command: ./scraper.py

  keeper:
    build: keeper/
    ports:
      - 5000:5000
    command: ./database_api.py
    depends_on:
      - reaper

  master:
    build: master/
    ports:
      - 8080:8080
    command: ./master.py
    depends_on:
      - reaper
      - keeper

